"use strict";
exports.__esModule = true;
var express = require('express');
var routes = express.Router();
var ClienteController = require('./controllers/ClienteController');
routes.get('/clientes', ClienteController.index);
routes.post('/clientes', ClienteController.create);
routes.put('/clientes/:id', ClienteController.update);
routes["delete"]('/clientes/:id', ClienteController["delete"]);
exports["default"] = routes;
